name: Update thumbnails.json
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python ./.github/script/generate_json.py > thumbnails.json
          date > json_last_updated
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[ACTIONS] Update JSON"
          git push
